--- 
pipelines: 
  - 
    name: docker_build_pipeline
    steps: 
      - 
        configuration: 
          affinityGroup: docker_afgroup
          dockerFileLocation: "."
          dockerFileName: Dockerfile
          dockerImageName: docker.art.local/alpine37
          dockerImageTag: $run_number
          inputResources: 
            - 
              name: repo_docker_build_push
          integrations: 
            - 
              name: artimus
        name: docker_build
        type: DockerBuild
      - 
        configuration: 
          affinityGroup: docker_afgroup
          inputSteps: 
            - 
              name: docker_build
          integrations: 
            - 
              name: artimus
          targetRepository: docker-local
        name: docker_push
        type: DockerPush
      - 
        configuration: 
          inputSteps: 
            - 
              name: docker_push
          outputResources: 
            - 
              name: build_info_docker_build_push
        name: publish_build_info
        type: PublishBuildInfo
      - 
        configuration: 
          inputResources: 
            - 
              name: build_info_docker_build_push
              trigger: false
          waitUntilFinish: <boolean>
        execution: 
          onCancel: 
            - "echo \"Someone cancelled the job\""
          onComplete: 
            - "echo \"Cleaning up some stuff\""
          onFailure: 
            - "echo \"uh oh, something went wrong\""
          onStart: 
            - "echo \"Prepping build environment\""
          onSuccess: 
            - "echo \"Job well done!\""
        name: scan
        type: XrayScan
