pipelines:
  - name: docker_build_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_afgroup             # Execute build and push on the same node
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: docker.art.local/alpine37
          dockerImageTag: $run_number
          inputResources:
            - name: repo_docker_build_push
          integrations:
            - name: artimus
 
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: docker_afgroup             # Execute build and push on the same node
          targetRepository: docker-local
          integrations:
            - name: artimus
          inputSteps:
            - name: docker_build
 
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_docker_build_push
            
pipelines:
  - name:   docker_build_pipeline
    steps:
      - name: scan
        type: XrayScan
        configuration:
          #inherits from bash
          waitUntilFinish:         <boolean>  # default true
 
          inputResources:
            - name:         build_info_docker_build_push          # required
              trigger: false
        execution:
          onStart:
            - echo "Preparing for work..."
          onStart:
            - echo "Prepping build environment"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
